### ISSUE TITLE
无法连接到直播间

### ISSUE THREAD

**Issue by heqyoufree** [MicroCBer/LiveSongPlayer-MKII#1]
在直播间发送弹幕点歌无反应，查看console，没有有关输出，查看network，没有有关b站的链接

**Comment by std-microblock** [comment]
你需要点击`打开点歌姬`

**Comment by heqyoufree** [comment]
![image](https://user-images.githubusercontent.com/35979724/205478326-172eccb6-30d0-42ff-9ee9-4bdfaf82516b.png)
已打开

**Comment by std-microblock** [comment]
哦 想起来了 最近B站改了弹幕格式

下周修一下

**Comment by heqyoufree** [comment]
https://github.com/MicroCBer/LiveSongPlayer-MKII/blob/fe26e23b7870a95717d37106b433f5124e78a3d9/src/App.svelte#L72
改为
```javascript
if (cmd.startsWith("DANMU_MSG")) {
```

**Comment by heqyoufree** [comment]
Fixed
