### ISSUE TITLE
输入房间号后无法进行点歌

### ISSUE THREAD

**Issue by Darling-neko** [MicroCBer/LiveSongPlayer-MKII#4]
在直播间号中输入了我的b站直播房间号后，在弹幕中发送“点歌xxx”，“play xxx”，“!点歌xxx”，“!play xxx”都没有任何反应，无法进行点歌

**Comment by Darling-neko** [comment]
仅可以在直播间25948785进行点歌，是有效果的，把房间号改成自己的，回车后也没有效果，我修改了数据文件下根目录的“main.js”和src中“App.svelte”的配置文件，但是保存后还是没有效果，进行插件重启后，发现配置文件的房间号还是变回了25948785

**Comment by std-microblock** [comment]
修改直播间id后需要按 Enter 生效
