### ISSUE TITLE
点歌后直接替换了现有歌曲

### ISSUE THREAD

**Issue by 6DDUU6** [MicroCBer/LiveSongPlayer-MKII#5]
wyy版本：2.10.12
点歌后直接替换了现在播放的歌曲，没有添加到右边列表里。

不知道怎么弄的成功了一次，但是重载插件后又不行了。

**Comment by std-microblock** [comment]
预期行为是：若当前播放的歌曲为自动播放/主播切的，那么点歌会直接播放
若当前播放的歌曲是弹幕点的，则不会
